In [1]:
import torch

## Exercise 1

* Create a 1D tensor from a Python list

* Create a 2D tensor of zeros with shape (3, 4)

* Create a 3D tensor of random values between 0 and 1 with shape (2, 3, 4)

* Create a tensor of ones with the same shape as the random tensor

* Print the shape, dtype, and device of each tensor

In [2]:
# Creating a python list
my_list= [1,2,3,4,5]
# Creating a 1D tensor from the list
tensor_from_list= torch.tensor(my_list, dtype= torch.float16)
tensor_from_list

tensor([1., 2., 3., 4., 5.], dtype=torch.float16)

In [3]:
# Creating a 2D tensor of zeros with shape (3,4)
zeros= torch.zeros(size= (3,4), dtype= torch.float16)
print(zeros)
print(zeros.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float16)
torch.Size([3, 4])


In [4]:
upper_bound= 1
lower_bound= 0

rand_tensor= (upper_bound - lower_bound) * torch.rand(size= (2,3,4))

print(f"Tensor: {rand_tensor}")
print(f"Shape: {rand_tensor.shape}")

Tensor: tensor([[[0.8201, 0.6196, 0.9309, 0.8735],
         [0.3843, 0.6424, 0.9878, 0.3363],
         [0.8443, 0.9954, 0.3878, 0.9327]],

        [[0.8179, 0.1278, 0.1536, 0.0688],
         [0.3725, 0.8183, 0.6082, 0.7560],
         [0.1133, 0.9141, 0.8748, 0.6121]]])
Shape: torch.Size([2, 3, 4])


In [5]:
ones_like_rand= torch.ones_like(rand_tensor)

print(f"Tensor: {ones_like_rand}")
print(f"Shape: {ones_like_rand.shape}")

Tensor: tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
Shape: torch.Size([2, 3, 4])


In [6]:
print(f"Tensor 1: {tensor_from_list}")
print(f"Shape: {tensor_from_list.shape}")
print(f"dtype: {tensor_from_list.dtype}")
print(f"device: {tensor_from_list.device}")
print("-"*20)

print(f"Tensor 2: {zeros}")
print(f"Shape: {zeros.shape}")
print(f"dtype: {zeros.dtype}")
print(f"device: {zeros.device}")
print("-"*20)

print(f"Tensor 3: {rand_tensor}")
print(f"Shape: {rand_tensor.shape}")
print(f"dtype: {rand_tensor.dtype}")
print(f"device: {rand_tensor.device}")
print("-"*20)

print(f"Tensor 4: {ones_like_rand}")
print(f"Shape: {ones_like_rand.shape}")
print(f"dtype: {ones_like_rand.dtype}")
print(f"device: {ones_like_rand.device}")
print("-"*20)

Tensor 1: tensor([1., 2., 3., 4., 5.], dtype=torch.float16)
Shape: torch.Size([5])
dtype: torch.float16
device: cpu
--------------------
Tensor 2: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float16)
Shape: torch.Size([3, 4])
dtype: torch.float16
device: cpu
--------------------
Tensor 3: tensor([[[0.8201, 0.6196, 0.9309, 0.8735],
         [0.3843, 0.6424, 0.9878, 0.3363],
         [0.8443, 0.9954, 0.3878, 0.9327]],

        [[0.8179, 0.1278, 0.1536, 0.0688],
         [0.3725, 0.8183, 0.6082, 0.7560],
         [0.1133, 0.9141, 0.8748, 0.6121]]])
Shape: torch.Size([2, 3, 4])
dtype: torch.float32
device: cpu
--------------------
Tensor 4: tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
Shape: torch.Size([2, 3, 4])
dtype: torch.float32
device: cpu
--------------------


## Exercise 2: Tensor Shapes and Reshaping
* 1. Create a 1D tensor with 12 elements
* 2. Reshape it to a 2D tensor of shape (3, 4)
* 3. Reshape it to a 3D tensor of shape (2, 2, 3)
* 4. Use view() to create a tensor of shape (6, 2)
* 5. Use unsqueeze() to add a dimension at position 0
* 6. Use squeeze() to remove any dimension of size 1

In [7]:
# 1D Tensor with 12 elements
elements_list= [2,5,1,9,2,6.6,72,8.8,25,4,3,25]
elements_tensor= torch.tensor(elements_list)
print(f"Starting Tensor: {elements_tensor}")
print(f"Starting Shape: {elements_tensor.shape}")
print("-" * 20)

reshaped_two_d= elements_tensor.reshape(shape= (3, 4))
print(f"Reshaped 2D Tensor: {reshaped_two_d}")
print(f"Shape after reshaping to 2D: {reshaped_two_d.shape}")
print("-" * 20)

reshaped_three_d= reshaped_two_d.reshape(shape= (2,2,3))
print(f"Reshaped 3D Tensor: {reshaped_three_d}")
print(f"Shape after reshaping to 3D: {reshaped_three_d.shape}")

Starting Tensor: tensor([ 2.0000,  5.0000,  1.0000,  9.0000,  2.0000,  6.6000, 72.0000,  8.8000,
        25.0000,  4.0000,  3.0000, 25.0000])
Starting Shape: torch.Size([12])
--------------------
Reshaped 2D Tensor: tensor([[ 2.0000,  5.0000,  1.0000,  9.0000],
        [ 2.0000,  6.6000, 72.0000,  8.8000],
        [25.0000,  4.0000,  3.0000, 25.0000]])
Shape after reshaping to 2D: torch.Size([3, 4])
--------------------
Reshaped 3D Tensor: tensor([[[ 2.0000,  5.0000,  1.0000],
         [ 9.0000,  2.0000,  6.6000]],

        [[72.0000,  8.8000, 25.0000],
         [ 4.0000,  3.0000, 25.0000]]])
Shape after reshaping to 3D: torch.Size([2, 2, 3])


In [8]:
new_tensor_view= reshaped_three_d.view(6,2)
print(f"New (6,2) Tensor using view: {new_tensor_view}")
print(f"Shape: {new_tensor_view.shape}")
new_tensor_view_unsqueezed= new_tensor_view.unsqueeze(dim= 0)
print(f"Unsqueezed: {new_tensor_view_unsqueezed}")
print(f"Unsqueezed shape: {new_tensor_view_unsqueezed.shape}")
new_tensor_view_squeezed= new_tensor_view_unsqueezed.squeeze()
print(f"Squeezed back to original: {new_tensor_view_squeezed}")
print(f"Squeezed shape to original: {new_tensor_view_squeezed.shape}")

New (6,2) Tensor using view: tensor([[ 2.0000,  5.0000],
        [ 1.0000,  9.0000],
        [ 2.0000,  6.6000],
        [72.0000,  8.8000],
        [25.0000,  4.0000],
        [ 3.0000, 25.0000]])
Shape: torch.Size([6, 2])
Unsqueezed: tensor([[[ 2.0000,  5.0000],
         [ 1.0000,  9.0000],
         [ 2.0000,  6.6000],
         [72.0000,  8.8000],
         [25.0000,  4.0000],
         [ 3.0000, 25.0000]]])
Unsqueezed shape: torch.Size([1, 6, 2])
Squeezed back to original: tensor([[ 2.0000,  5.0000],
        [ 1.0000,  9.0000],
        [ 2.0000,  6.6000],
        [72.0000,  8.8000],
        [25.0000,  4.0000],
        [ 3.0000, 25.0000]])
Squeezed shape to original: torch.Size([6, 2])


## Exercise 3: Basic Broadcasting
* Create a tensor A of shape (3, 1)

* Create a tensor B of shape (1, 4)

* Add A and B and observe the result

* Create a tensor C of shape (3, 4)

* Multiply C by a scalar (tensor of shape ())

* Create a tensor D of shape (4,)

* Add C and D and observe the result

In [9]:
upper_bound= 30
lower_bound= 5
A= (upper_bound - lower_bound) * torch.rand(size=(3,1), dtype= torch.float16)
B= (upper_bound - lower_bound) * torch.rand(size=(1,4), dtype= torch.float16)
print(f"Tensor A: {A}")
print(f"Tensor A Shape: {A.shape}")
print("-"*10)
print(f"Tensor B: {B}")
print(f"Tesnor B Shape: {B.shape}")

A_plus_B= A + B
print(f"Tensor A+B: {A_plus_B}")

Tensor A: tensor([[11.8125],
        [11.1484],
        [ 5.7266]], dtype=torch.float16)
Tensor A Shape: torch.Size([3, 1])
----------
Tensor B: tensor([[ 5.6523, 13.1875,  6.3711,  5.9336]], dtype=torch.float16)
Tesnor B Shape: torch.Size([1, 4])
Tensor A+B: tensor([[17.4688, 25.0000, 18.1875, 17.7500],
        [16.7969, 24.3438, 17.5156, 17.0781],
        [11.3750, 18.9062, 12.0938, 11.6562]], dtype=torch.float16)


In [10]:
C= (upper_bound - lower_bound) * torch.rand(size= (3, 4), dtype= torch.float16)
scalar_k= torch.tensor(2)
print(f"Tensor C: {C}")
print(f"Tensor C Shape: {C.shape}")
print(f"Scalar k: {scalar_k} | Shape: {scalar_k.shape}")
print(f"kC: {scalar_k * C} | Shape: {(scalar_k * C).shape}")

Tensor C: tensor([[20.9219,  4.3828,  2.3066, 12.8750],
        [19.5469, 17.7188, 20.7344,  2.6250],
        [18.3281, 10.3750, 19.4688,  8.8047]], dtype=torch.float16)
Tensor C Shape: torch.Size([3, 4])
Scalar k: 2 | Shape: torch.Size([])
kC: tensor([[41.8438,  8.7656,  4.6133, 25.7500],
        [39.0938, 35.4375, 41.4688,  5.2500],
        [36.6562, 20.7500, 38.9375, 17.6094]], dtype=torch.float16) | Shape: torch.Size([3, 4])


In [11]:
D= (upper_bound - lower_bound) * torch.rand(size=(4,))
print(f"Tensor D: {D}")
print(f"Tensor D Shape: {D.shape}")
print(f"Tensor C+D: {C + D} | Shape: {(C + D).shape}")

Tensor D: tensor([12.9076, 15.5646, 15.0989,  5.7806])
Tensor D Shape: torch.Size([4])
Tensor C+D: tensor([[33.8295, 19.9474, 17.4056, 18.6556],
        [32.4545, 33.2833, 35.8333,  8.4056],
        [31.2358, 25.9396, 34.5677, 14.5853]]) | Shape: torch.Size([3, 4])


## Exercise 4: Advanced Broadcasting Operations

* Create a tensor X of shape (5, 4) with random values
 
* Create a tensor Y of shape (4,) with values [1, 2, 3, 4]
 
* Subtract Y from each row of X
 
* Create a tensor Z of shape (5, 1) with values [10, 20, 30, 40, 50]
 
* Add Z to each column of the result from step 3
 
* Create a tensor M of shape (3, 1, 4) and tensor N of shape (2, 4)
 
* Add M and N and explain the broadcasting

In [12]:
upper_bound= 10
lower_bound= 0
X= (upper_bound - lower_bound) * torch.rand(size=(5, 4))
Y= torch.tensor([1,2,3,4])
X_m_Y= X - Y
print(f"Tensor X: {X}")
print(f"Tensor Y: {Y}")
print(f"Tensor X - Y: {X_m_Y}")
print(f"X-Y Shape: {(X_m_Y).shape}")


Tensor X: tensor([[6.4715, 2.1144, 9.8830, 9.5979],
        [8.8961, 4.5710, 8.2781, 7.4386],
        [8.0124, 1.4778, 2.3078, 9.3694],
        [4.8934, 6.5349, 2.8707, 0.7675],
        [6.8197, 3.3112, 3.8701, 4.6595]])
Tensor Y: tensor([1, 2, 3, 4])
Tensor X - Y: tensor([[ 5.4715,  0.1144,  6.8830,  5.5979],
        [ 7.8961,  2.5710,  5.2781,  3.4386],
        [ 7.0124, -0.5222, -0.6922,  5.3694],
        [ 3.8934,  4.5349, -0.1293, -3.2325],
        [ 5.8197,  1.3112,  0.8701,  0.6595]])
X-Y Shape: torch.Size([5, 4])


In [13]:
Z= torch.tensor([10,20,30,40,50])
for i in range(X_m_Y.shape[1]):
    print(f"Z + Col {i + 1}= {Z + X_m_Y[:,i]}")
    


Z + Col 1= tensor([15.4715, 27.8961, 37.0124, 43.8934, 55.8197])
Z + Col 2= tensor([10.1144, 22.5710, 29.4778, 44.5349, 51.3112])
Z + Col 3= tensor([16.8830, 25.2781, 29.3078, 39.8707, 50.8701])
Z + Col 4= tensor([15.5979, 23.4386, 35.3694, 36.7675, 50.6595])


In [14]:
M= (upper_bound - lower_bound) * torch.rand(size= (3, 1, 4))
N= (upper_bound - lower_bound) * torch.rand(size=(2,4))
print(f"Tensor M: {M}")
print(f"Tensor M Shape: {M.shape}")
print("-"*20)
print(f"Tensor N: {N}")
print(f"Tensor N Shape: {N.shape}")
result_mn = M + N
print("\nResult of M + N:\n", result_mn)
print("Shape of result:", result_mn.shape)
print("\nBroadcasting explanation:")
print("- M (3, 1, 4) is broadcasted to (3, 2, 4) by repeating along dimension 1")
print("- N (2, 4) is broadcasted to (1, 2, 4) and then to (3, 2, 4) by repeating along dimension 0")
print("- Element-wise addition is performed on the broadcasted tensors")


Tensor M: tensor([[[2.3394, 9.3994, 0.0149, 1.6941]],

        [[7.8083, 7.4877, 9.0345, 5.9620]],

        [[0.9765, 2.1690, 2.7237, 5.9263]]])
Tensor M Shape: torch.Size([3, 1, 4])
--------------------
Tensor N: tensor([[8.1271, 1.0940, 0.7872, 2.8865],
        [3.0781, 5.5412, 3.4205, 4.2151]])
Tensor N Shape: torch.Size([2, 4])

Result of M + N:
 tensor([[[10.4665, 10.4934,  0.8021,  4.5806],
         [ 5.4176, 14.9406,  3.4354,  5.9092]],

        [[15.9354,  8.5817,  9.8217,  8.8484],
         [10.8864, 13.0289, 12.4549, 10.1771]],

        [[ 9.1036,  3.2629,  3.5109,  8.8128],
         [ 4.0547,  7.7102,  6.1442, 10.1414]]])
Shape of result: torch.Size([3, 2, 4])

Broadcasting explanation:
- M (3, 1, 4) is broadcasted to (3, 2, 4) by repeating along dimension 1
- N (2, 4) is broadcasted to (1, 2, 4) and then to (3, 2, 4) by repeating along dimension 0
- Element-wise addition is performed on the broadcasted tensors


## Exercise 5: Practical Application - Normalizing Data

* Create a tensor representing a dataset of shape (100, 5) with random values between 0 and 100

* Calculate the mean of each column (feature)

* Calculate the standard deviation of each column (feature)

* Normalize the dataset by subtracting the mean and dividing by the standard deviation for each column

* Verify that the normalized data has approximately zero mean and unit standard deviation for each column

In [15]:
upper_bound= 100
torch.manual_seed(42)
dataset= upper_bound * torch.rand(size= (100, 5))
print(f"Original Data First 5 Rows: {dataset[:5]}")
print(f"Dataset Shape: {dataset.shape}")
mean= torch.mean(dataset, dim= 0)
print(f"Features Mean: {mean}")
std= torch.std(dataset, dim= 0)
print(f"Features Standard Deviation: {std}")
normalized_dataset= (dataset - mean) / std
print(f"Normalized Data First 5 Rows: {normalized_dataset[:5]}")


Original Data First 5 Rows: tensor([[88.2269, 91.5004, 38.2864, 95.9306, 39.0448],
        [60.0895, 25.6572, 79.3641, 94.0771, 13.3186],
        [93.4598, 59.3580, 86.9404, 56.7715, 74.1094],
        [42.9404, 88.5443, 57.3904, 26.6580, 62.7449],
        [26.9632, 44.1364, 29.6921, 83.1685, 10.5315]])
Dataset Shape: torch.Size([100, 5])
Features Mean: tensor([49.8762, 45.0017, 50.1827, 50.0841, 43.4298])
Features Standard Deviation: tensor([28.1781, 27.5750, 29.9273, 29.6868, 28.9575])
Normalized Data First 5 Rows: tensor([[ 1.3610,  1.6863, -0.3975,  1.5443, -0.1514],
        [ 0.3625, -0.7015,  0.9751,  1.4819, -1.0398],
        [ 1.5467,  0.5206,  1.2282,  0.2253,  1.0595],
        [-0.2461,  1.5791,  0.2408, -0.7891,  0.6670],
        [-0.8131, -0.0314, -0.6847,  1.1144, -1.1361]])


In [17]:
# Check if the means are close to zero and standard deviations are close to 1
normalized_mean= torch.mean(normalized_dataset, dim= 0)
normalized_std= torch.std(normalized_dataset, dim= 0)
print("\nVerification:")
print("Means are close to zero:", torch.allclose(normalized_mean, torch.zeros_like(normalized_mean), atol=1e-6))
print("Standard deviations are close to one:", torch.allclose(normalized_std, torch.ones_like(normalized_std), atol=1e-6))


Verification:
Means are close to zero: True
Standard deviations are close to one: True


## Exercise 6: Broadcasting with Different Data Types

* Create a tensor A of shape (3, 4) with float32 values

* Create a tensor B of shape (4,) with int32 values

* Try to add A and B and observe what happens

* Create a tensor C on CPU and a tensor D on GPU (if CUDA is available)

* Try to add C and D and observe what happen
s

* Fix any issues and successfully perform the operations

In [24]:
A= 2 * torch.rand(size= (3, 4), dtype= torch.float32)
B= torch.tensor([1,2,3,4], dtype= torch.int32)
try:
    result = A + B
    print("\nResult of A + B:\n", result)
    print("Data type of result:", result.dtype)
    print("\nObservation: PyTorch automatically upcasts the int32 tensor to float32")
except Exception as e:
    print("\nError:", e)


Result of A + B:
 tensor([[1.3862, 3.3813, 4.8341, 4.7025],
        [1.7091, 3.5340, 3.5066, 4.5272],
        [2.6161, 2.1287, 4.1223, 5.8834]])
Data type of result: torch.float32

Observation: PyTorch automatically upcasts the int32 tensor to float32


In [26]:
C= torch.tensor([1,2,3,4], device= torch.device('cpu'))
D= torch.tensor([3,4,5,6], device= torch.device('cuda'))

try:
    result= C+D
    print("\nResult of A + B:\n", result)
    print("Data type of result:", result.dtype)
except Exception as e:
    print("\nError:", e)


Error: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!


In [31]:
# Fixing the problem
device= D.device
C= C.to(device)
try:
    result= C+D
    print("\nResult of A + B:\n", result)
    print("Data type of result:", result.dtype)
except Exception as e:
    print("\nError:", e)



Result of A + B:
 tensor([ 4,  6,  8, 10], device='cuda:0')
Data type of result: torch.int64
